const savedRaw=localStorage.getItem("nepalJobsSaved")||"[]";let savedIds=[];try{savedIds=JSON.parse(savedRaw);if(!Array.isArray(savedIds))savedIds=[]}catch{savedIds=[]}const state={jobs:[],filtered:[],saved:new Set(savedIds)};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmtDate=s=>{if(!s)return"—";const d=new Date(s+"T00:00:00");return isNaN(d)?"—":d.toLocaleDateString("ne-NP",{year:"numeric",month:"short",day:"numeric"})};
const daysLeft=s=>{const d=new Date(s+"T23:59:59"),n=new Date();return Math.ceil((d-n)/86400000)};
function initials(s){return String(s||"").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"JP"}
function save(id){if(state.saved.has(id))state.saved.delete(id);else state.saved.add(id);localStorage.setItem("nepalJobsSaved",JSON.stringify([...state.saved]));render()}
function values(){return{q:$("heroSearch").value.trim().toLowerCase(),category:$("category").value,qualification:$("qualification").value,location:$("location").value,experience:$("experience").value,remote:$("remote").checked}}
function matches(j,v){const hay=[j.title,j.organization,j.location,j.description,(j.skills||[]).join(" "),j.category,j.qualification].join(" ").toLowerCase();return(!v.q||hay.includes(v.q))&&(!v.category||j.category===v.category)&&(!v.qualification||j.qualification.includes(v.qualification))&&(!v.location||j.location===v.location)&&(!v.experience||j.experience===v.experience)&&(!v.remote||j.remote)}
function render(){const v=values();state.filtered=state.jobs.filter(j=>matches(j,v));const sort=$("sort").value;
state.filtered.sort((a,b)=>sort==="salary"?Number(b.salaryMax||0)-Number(a.salaryMax||0):sort==="deadline"?String(a.deadline).localeCompare(String(b.deadline)):String(b.posted).localeCompare(String(a.posted)));
$("resultText").textContent=state.filtered.length+" job"+(state.filtered.length===1?"":"s")+" found";
$("jobGrid").innerHTML=state.filtered.map(card).join("");$("emptyState").hidden=state.filtered.length>0;
$("activeFilters").innerHTML=[["category","Category: "+v.category],["qualification","Qualification: "+v.qualification],["location","Location: "+v.location],["experience","Experience: "+v.experience],["remote","Remote"]].filter(x=>v[x[0]]).map(x=>"<button data-clear=\""+esc(x[0])+"\">"+esc(x[1])+" ×</button>").join("");
document.querySelectorAll("[data-save]").forEach(x=>x.onclick=()=>save(x.dataset.save));
document.querySelectorAll("[data-details]").forEach(x=>x.onclick=()=>openModal(x.dataset.details));
document.querySelectorAll("[data-clear]").forEach(x=>x.onclick=()=>{const k=x.dataset.clear;if(k==="remote")$("remote").checked=false;else $(k).value="";render()});
}
function jobUrl(j){const s=String(j.slug||((j.title||"job")+"-"+(j.organization||""))).normalize("NFKD").toLowerCase().replace(/[^\p{Letter}\p{Number}\s-]/gu,"").trim().replace(/\s+/g,"-").replace(/-+/g,"-").slice(0,70)||"job";return "/"+s+"/"}
function card(j){const left=daysLeft(j.deadline),urgent=left>=0&&left<=5;return "<article class=\"job-card\"><div class=\"job-top\"><div class=\"job-org\"><span class=\"org-logo\">"+esc(initials(j.organization))+"</span><div><div class=\"org-name\">"+esc(j.organization)+(j.verified?" <span class=\"verified\">✓ Verified source</span>":"")+"</div></div></div><button class=\"save "+(state.saved.has(j.id)?"saved":"")+"\" data-save=\""+esc(j.id)+"\" aria-label=\"Save job\">"+(state.saved.has(j.id)?"★":"☆")+"</button></div><h3 class=\"job-title\">"+esc(j.title)+"</h3><div class=\"badges\"><span class=\"badge cat\">"+esc(j.category)+"</span><span class=\"badge\">"+esc(j.type||"Full-time")+"</span></div><div class=\"job-meta\"><div class=\"meta\"><span>Qualification</span><strong>"+esc(j.qualification)+"</strong></div><div class=\"meta\"><span>Experience</span><strong>"+esc(j.experience)+"</strong></div><div class=\"meta\"><span>Location</span><strong>"+esc(j.location)+"</strong></div><div class=\"meta\"><span>Salary</span><strong>"+esc(j.salary||"Not disclosed")+"</strong></div></div><div class=\"deadline\">Deadline: <b>"+fmtDate(j.deadline)+"</b> "+(urgent?"· <b>"+left+" day"+(left===1?"":"s")+" left</b>":"")+"</div><div class=\"job-actions\"><a class=\"details\" href=\""+esc(jobUrl(j))+"\">View details</a><a class=\"apply\" href=\""+esc(j.applyUrl)+"\" target=\"_blank\" rel=\"noopener noreferrer\">Apply ↗</a></div></article>"}
function openModal(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;const req=(j.requirements||[]).map(x=>"<li>"+esc(x)+"</li>").join("");$("modalContent").innerHTML="<div class=\"eyebrow\">"+esc(j.category)+"</div><h2>"+esc(j.title)+"</h2><div class=\"modal-org\">"+esc(j.organization)+" · "+esc(j.location)+(j.verified?" · ✓ Verified source":"")+"</div><div class=\"modal-section\"><h3>Job overview</h3><p>"+esc(j.description)+"</p></div><div class=\"modal-section\"><h3>Requirements</h3><ul>"+req+"</ul></div><div class=\"modal-section\"><h3>Skills</h3><p>"+esc((j.skills||[]).join(" · ")||"Not specified")+"</p></div><div class=\"modal-section\"><h3>Application</h3><p><b>Deadline:</b> "+fmtDate(j.deadline)+"<br><b>Salary:</b> "+esc(j.salary||"Not disclosed")+"<br><b>Source:</b> "+esc(j.source||"Employer")+"</p></div><a class=\"modal-apply\" href=\""+esc(j.applyUrl)+"\" target=\"_blank\" rel=\"noopener noreferrer\">Apply / View official notice ↗</a>";$("jobModal").classList.add("open");$("jobModal").setAttribute("aria-hidden","false")}
function clearAll(){["category","qualification","location","experience"].forEach(x=>$(x).value="");$("remote").checked=false;render()}
async function init(){try{const r=await fetch("/jobs.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);const data=await r.json();if(!Array.isArray(data))throw new Error("Invalid jobs data");state.jobs=data;$("totalJobs").textContent=state.jobs.length;$("openJobs").textContent=state.jobs.filter(j=>daysLeft(j.deadline)>=0).length;$("orgCount").textContent=new Set(state.jobs.map(j=>j.organization)).size;$("quickCats").innerHTML=["सरकारी","निजी","संस्था / NGO / INGO","बैंकिङ / वित्त","IT / Technology","शिक्षा"].map(c=>"<button data-cat=\""+esc(c)+"\">"+esc(c)+"</button>").join("");document.querySelectorAll("[data-cat]").forEach(x=>x.onclick=()=>{$("category").value=x.dataset.cat;document.getElementById("jobs").scrollIntoView({behavior:"smooth"});render()});render()}catch(e){console.error("Jobs portal load failed",e);$("resultText").textContent="Jobs data could not be loaded. Please refresh once.";$("jobGrid").innerHTML="<div class=\"empty\"><h3>Job data temporarily unavailable</h3><p>The portal is online, but the jobs feed could not be read.</p><button onclick=\"location.reload()\">Refresh</button></div>"}}
["heroSearch","category","qualification","location","experience","remote","sort"].forEach(id=>$(id).addEventListener(id==="heroSearch"?"input":"change",render));
$("heroSearchBtn").onclick=()=>{$("jobs").scrollIntoView({behavior:"smooth"});render()};$("clearFilters").onclick=clearAll;$("emptyClear").onclick=clearAll;
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{$("jobModal").classList.remove("open");$("jobModal").setAttribute("aria-hidden","true")});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){$("jobModal").classList.remove("open");$("jobModal").setAttribute("aria-hidden","true")}});
init();